[package]
name = "finder"
version = "2.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
exitcode = "1.1.2"
lazy_static = "1.4.0"
regex = "1.8.3"
walkdir = "2.3.3"
