[package]
name = "finder"
version = "1.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
exitcode = "1.1.2"
fileops = { path = "../fileops" }
